version: '3.2'

services:
  transactions-api:
    image: transactions-api
    build:
      context: transactions-api/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    links:
      - stub-dev-db
    environment:
      - UH_URL=Server=stub-dev-db;Database=uhsimulator;User Id='sa';Password='Rooty-Tooty';
  stub-dev-db:
    image: 775052747630.dkr.ecr.eu-west-2.amazonaws.com/hackney/universal-housing-simulator-loaded
    ports:
      - 1433:1433

  transactions-api-test:
    image: transactions-api-test
    build:
      context: .
      dockerfile: transactions-api.Tests/Dockerfile
    environment:
      - TEST_UH_URL=Server=stub-test-db;Database=uhsimulator;User Id='sa';Password='Rooty-Tooty';
    links:
      - stub-test-db
  stub-test-db:
    image: 775052747630.dkr.ecr.eu-west-2.amazonaws.com/hackney/universal-housing-simulator
    ports:
      - 1433:1433
